// Read all .env* files in the root folder and add them to process.env
// See https://github.com/kerimdzhanov/dotenv-flow for more details
require('dotenv-flow').config();

module.exports = {
  HOME_URL: process.env.SEMAPPS_HOME_URL,
  FRONTOFFICE_URL: process.env.SEMAPPS_FRONTOFFICE_URL,
  BACKOFFICE_URL: process.env.SEMAPPS_BACKOFFICE_URL,
  PORT: process.env.SEMAPPS_PORT,
  INSTANCE_NAME: process.env.SEMAPPS_INSTANCE_NAME,
  INSTANCE_DESCRIPTION: process.env.SEMAPPS_INSTANCE_DESCRIPTION,
  WORDPRESS_API_BASE: process.env.SEMAPPS_WORDPRESS_API_BASE,
  WORDPRESS_API_USER: process.env.SEMAPPS_WORDPRESS_API_USER,
  WORDPRESS_API_PASSWORD: process.env.SEMAPPS_WORDPRESS_API_PASSWORD,
  FUSEKI_BASE: process.env.SEMAPPS_FUSEKI_BASE,
  SPARQL_ENDPOINT: process.env.SEMAPPS_SPARQL_ENDPOINT,
  MAIN_DATASET: process.env.SEMAPPS_MAIN_DATASET,
  JENA_USER: process.env.SEMAPPS_JENA_USER,
  JENA_PASSWORD: process.env.SEMAPPS_JENA_PASSWORD,
  REDIS_CACHE_URL: process.env.SEMAPPS_REDIS_CACHE_URL,
  FROM_EMAIL: process.env.SEMAPPS_FROM_EMAIL,
  FROM_NAME: process.env.SEMAPPS_FROM_NAME,
  SMTP_HOST: process.env.SEMAPPS_SMTP_HOST,
  SMTP_PORT: parseInt(process.env.SEMAPPS_SMTP_PORT, 10),
  SMTP_SECURE: process.env.SEMAPPS_SMTP_SECURE === 'true',
  SMTP_USER: process.env.SEMAPPS_SMTP_USER,
  SMTP_PASS: process.env.SEMAPPS_SMTP_PASS,
  BACKUP_SERVER_PATH: process.env.SEMAPPS_BACKUP_SERVER_PATH,
  AUTH_ACCOUNTS_DATASET_NAME: process.env.SEMAPPS_AUTH_ACCOUNTS_DATASET_NAME
};
